version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: threadspace_user
      POSTGRES_PASSWORD: threadspace_password
      POSTGRES_DB: threadspace_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
